HalfBlockImage: fix error handling
TypeError: expected string or bytes-like object, got 'HTTPStatusError'

The exception needs to be cast to a string.